/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Martin
 */
public class Aparatos extends javax.swing.JFrame {

    /**
     * Creates new form Socio
     */
    public Aparatos() {
        initComponents();
    }
     Connection connection;
    PreparedStatement pst;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        IdAparat = new javax.swing.JTextField();
        EstaApa = new javax.swing.JTextField();
        IdSalApa = new javax.swing.JTextField();
        DescrpApa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setForeground(new java.awt.Color(22, 97, 172));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton Guardar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 80, 50));

        IdAparat.setBackground(new java.awt.Color(49, 97, 131));
        IdAparat.setForeground(new java.awt.Color(255, 255, 255));
        IdAparat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdAparatActionPerformed(evt);
            }
        });
        getContentPane().add(IdAparat, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 210, 30));

        EstaApa.setBackground(new java.awt.Color(49, 97, 131));
        EstaApa.setForeground(new java.awt.Color(255, 255, 255));
        EstaApa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstaApaActionPerformed(evt);
            }
        });
        getContentPane().add(EstaApa, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, 220, 30));

        IdSalApa.setBackground(new java.awt.Color(49, 97, 131));
        IdSalApa.setForeground(new java.awt.Color(255, 255, 255));
        IdSalApa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdSalApaActionPerformed(evt);
            }
        });
        getContentPane().add(IdSalApa, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 440, 190, 30));

        DescrpApa.setBackground(new java.awt.Color(49, 97, 131));
        DescrpApa.setForeground(new java.awt.Color(255, 255, 255));
        DescrpApa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescrpApaActionPerformed(evt);
            }
        });
        getContentPane().add(DescrpApa, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 300, 30));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Aparatos.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            connection = Conexion.getConnection();  //Establecer conexiÃ³n
            pst = connection.prepareStatement("INSERT INTO aparto (CodAparato, Descpcion, Estado, IdSala, Sala_idSala) VALUES (? , ? , ? , ? , ? )");
            pst.setString(1, this.IdAparat.getText());
            pst.setString(2, this.DescrpApa.getText());
            pst.setString(3, this.EstaApa.getText());
            pst.setString(4,this.IdSalApa.getText());
            pst.setString(5,this.IdSalApa.getText());
             
            String cadena = this.IdAparat.getText();
            if (cadena.equals("")) {
                JOptionPane.showMessageDialog(null, "El Numero de aparato es Obligatorio!");
            } else {
                int res = pst.executeUpdate();
                if (res > 0) {
                    JOptionPane.showMessageDialog(null, "Datos Almacenados correctamente!");
                } else {
                    JOptionPane.showMessageDialog(null, "Datos No Almacenados!");
                }
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }
        
       this.IdAparat.setText("");
          this.DescrpApa.setText("");
             this.IdSalApa.setText("");
             this.EstaApa.setText("");
         
           
        
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void IdAparatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdAparatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdAparatActionPerformed

    private void EstaApaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstaApaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstaApaActionPerformed

    private void IdSalApaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdSalApaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdSalApaActionPerformed

    private void DescrpApaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescrpApaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescrpApaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aparatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aparatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aparatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aparatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aparatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DescrpApa;
    private javax.swing.JTextField EstaApa;
    private javax.swing.JTextField IdAparat;
    private javax.swing.JTextField IdSalApa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
