/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Martin
 */
public class Socio extends javax.swing.JFrame {

    /**
     * Creates new form Socio
     */
    public Socio() {
        initComponents();
    }
     Connection connection;
    PreparedStatement pst;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        NumSocio = new javax.swing.JTextField();
        NomSocio = new javax.swing.JTextField();
        DirecSocio = new javax.swing.JTextField();
        CiudSocio = new javax.swing.JTextField();
        Apellido = new javax.swing.JTextField();
        CuentSocio = new javax.swing.JTextField();
        ProfSocio = new javax.swing.JTextField();
        TelfSocio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setForeground(new java.awt.Color(22, 97, 172));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Boton Guardar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 80, 50));

        NumSocio.setBackground(new java.awt.Color(49, 97, 131));
        NumSocio.setForeground(new java.awt.Color(255, 255, 255));
        NumSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumSocioActionPerformed(evt);
            }
        });
        getContentPane().add(NumSocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 220, 30));

        NomSocio.setBackground(new java.awt.Color(49, 97, 131));
        NomSocio.setForeground(new java.awt.Color(255, 255, 255));
        NomSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomSocioActionPerformed(evt);
            }
        });
        getContentPane().add(NomSocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 215, 30));

        DirecSocio.setBackground(new java.awt.Color(49, 97, 131));
        DirecSocio.setForeground(new java.awt.Color(255, 255, 255));
        DirecSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DirecSocioActionPerformed(evt);
            }
        });
        getContentPane().add(DirecSocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 310, 30));

        CiudSocio.setBackground(new java.awt.Color(49, 97, 131));
        CiudSocio.setForeground(new java.awt.Color(255, 255, 255));
        CiudSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CiudSocioActionPerformed(evt);
            }
        });
        getContentPane().add(CiudSocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 550, 220, 30));

        Apellido.setBackground(new java.awt.Color(49, 97, 131));
        Apellido.setForeground(new java.awt.Color(255, 255, 255));
        Apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidoActionPerformed(evt);
            }
        });
        getContentPane().add(Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 220, 30));

        CuentSocio.setBackground(new java.awt.Color(49, 97, 131));
        CuentSocio.setForeground(new java.awt.Color(255, 255, 255));
        CuentSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentSocioActionPerformed(evt);
            }
        });
        getContentPane().add(CuentSocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 550, 220, 30));

        ProfSocio.setBackground(new java.awt.Color(49, 97, 131));
        ProfSocio.setForeground(new java.awt.Color(255, 255, 255));
        ProfSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfSocioActionPerformed(evt);
            }
        });
        getContentPane().add(ProfSocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 480, 220, 30));

        TelfSocio.setBackground(new java.awt.Color(49, 97, 131));
        TelfSocio.setForeground(new java.awt.Color(255, 255, 255));
        TelfSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelfSocioActionPerformed(evt);
            }
        });
        getContentPane().add(TelfSocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 220, 30));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/socio.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            connection = Conexion.getConnection();  //Establecer conexiÃ³n
            pst = connection.prepareStatement("INSERT INTO socio (NumSocio, Nombre, Telf, Direccion,Profesion, CuenBanca,  IdCiudad, Ciudad_idCiudad) VALUES (?,? , ? , ? , ? , ? , ? ,?)");
            pst.setString(1, this.NumSocio.getText());
            pst.setString(2, this.NomSocio.getText());
            pst.setString(3, this.TelfSocio.getText());
            pst.setString(4,this.DirecSocio.getText());
            pst.setString(5,this.ProfSocio.getText());
             pst.setString(6,this.CuentSocio.getText());
             pst.setString(7,this.CiudSocio.getText());
          pst.setString(8,this.CiudSocio.getText());
            String cadena = this.NumSocio.getText();
            if (cadena.equals("")) {
                JOptionPane.showMessageDialog(null, "El Numero de Identificacion  es Obligatorio!");
            } else {
                int res = pst.executeUpdate();
                if (res > 0) {
                    JOptionPane.showMessageDialog(null, "Datos Almacenados correctamente!");
                } else {
                    JOptionPane.showMessageDialog(null, "Datos No Almacenados!");
                }
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }
        
       this.NumSocio.setText("");
          this.NomSocio.setText("");
             this.TelfSocio.setText("");
           this.DirecSocio.setText("");
          this.ProfSocio.setText("");
             this.CuentSocio.setText("");
             this.CiudSocio.setText("");
          this.CiudSocio.setText("");
           this.Apellido.setText("");
        
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void NumSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumSocioActionPerformed

    private void NomSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomSocioActionPerformed

    private void DirecSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DirecSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DirecSocioActionPerformed

    private void CiudSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CiudSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CiudSocioActionPerformed

    private void ApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidoActionPerformed

    private void CuentSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuentSocioActionPerformed

    private void ProfSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProfSocioActionPerformed

    private void TelfSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelfSocioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelfSocioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Socio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Socio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Socio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Socio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Socio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apellido;
    private javax.swing.JTextField CiudSocio;
    private javax.swing.JTextField CuentSocio;
    private javax.swing.JTextField DirecSocio;
    private javax.swing.JTextField NomSocio;
    private javax.swing.JTextField NumSocio;
    private javax.swing.JTextField ProfSocio;
    private javax.swing.JTextField TelfSocio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
